import type { Metadata } from "next";
import "./../../globals.css";
import { accounts } from "./data";
import { Layout } from "@/components/layout";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className="relative flex h-screen w-screen overflow-hidden">
            <Layout accounts={accounts}>{children}</Layout>
         </body>
      </html>
   );
}
