import { CourseProps } from "@/lib/types";

export const departments = [
   {
      departmentName: "Software Engineering",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Cyber Security",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Computer Science",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Information System",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Information Technology",
      faculty: "Computing",
      password: "secured",
   },
];

export const courses = [
   {
      courseCode: "SWE321",
      courseTitle: "Software Testing & Quality Assurance",
      department: "Software Engineering",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "SWE221",
   },
   {
      courseCode: "CSC1019",
      courseTitle: "Introduction to Computer Science",
      department: "Computer Science",
      level: "100",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "MAT202",
      courseTitle: "Linear Algebra",
      department: "Mathematics",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "MAT101",
   },
   {
      courseCode: "PHY301",
      courseTitle: "Modern Physics",
      department: "Physics",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "PHY201",
   },
   {
      courseCode: "ENG409",
      courseTitle: "Advanced English Composition",
      department: "English",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ENG301",
   },
   {
      courseCode: "CHE202",
      courseTitle: "Organic Chemistry",
      department: "Chemistry",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "CHE101",
   },
   {
      courseCode: "ECO302",
      courseTitle: "Macroeconomics",
      department: "Economics",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ECO201",
   },
   {
      courseCode: "PSY201",
      courseTitle: "Introduction to Psychology",
      department: "Psychology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "SOC319",
      courseTitle: "Sociological Theory I",
      department: "Sociology",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC301",
   },
   {
      courseCode: "BIO209",
      courseTitle: "Genetics I",
      department: "Biology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO101",
   },
   {
      courseCode: "ART301",
      courseTitle: "Art History I",
      department: "Art",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ART201",
   },
   {
      courseCode: "MUS409",
      courseTitle: "Music Composition I",
      department: "Music",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "MUS301",
   },
   {
      courseCode: "HIS201",
      courseTitle: "World History I",
      department: "History",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "HIS101",
   },
   {
      courseCode: "POL309",
      courseTitle: "International Relations I",
      department: "Political Science",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "POL201",
   },
   {
      courseCode: "PHI409",
      courseTitle: "Philosophical Ethics I",
      department: "Philosophy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHI301",
   },
   {
      courseCode: "GEO209",
      courseTitle: "Geography of Cities I",
      department: "Geography",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "GEO101",
   },
   {
      courseCode: "BUS309",
      courseTitle: "Business Ethics I",
      department: "Business",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "BUS201",
   },
   {
      courseCode: "ANT201",
      courseTitle: "Cultural Anthropology I",
      department: "Anthropology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "ARC409",
      courseTitle: "Architectural Design I",
      department: "Architecture",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ARC301",
   },
   {
      courseCode: "EDU309",
      courseTitle: "Educational Psychology I",
      department: "Education",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "EDU201",
   },
   {
      courseCode: "ENV209",
      courseTitle: "Environmental Science I",
      department: "Environmental Science",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "LING409",
      courseTitle: "Linguistics I",
      department: "Linguistics",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "LING301",
   },
   {
      courseCode: "MED202",
      courseTitle: "Media Studies",
      department: "Media Studies",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "MED101",
   },
   {
      courseCode: "NUR302",
      courseTitle: "Community Health Nursing",
      department: "Nursing",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "NUR201",
   },
   {
      courseCode: "PHARM409",
      courseTitle: "Pharmacology",
      department: "Pharmacy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHARM301",
   },
   {
      courseCode: "RAD209",
      courseTitle: "Radiology Techniques",
      department: "Radiology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "RAD101",
   },
   {
      courseCode: "SOC209",
      courseTitle: "Social Problems",
      department: "Sociology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC101",
   },
   {
      courseCode: "SWK409",
      courseTitle: "Social Work Practice",
      department: "Social Work",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "SWK301",
   },
   {
      courseCode: "THE309",
      courseTitle: "Theatre Arts",
      department: "Theatre Arts",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "THE201",
   },
   {
      courseCode: "AGR209",
      courseTitle: "Agricultural Economics",
      department: "Agricultural Economics",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "AGR101",
   },
   {
      courseCode: "BIO409",
      courseTitle: "Advanced Biology",
      department: "Biology",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO301",
   },
   {
      courseCode: "CHM209",
      courseTitle: "Inorganic Chemistry",
      department: "Chemistry",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "CHM101",
   },
   {
      courseCode: "ECO409",
      courseTitle: "Microeconomics",
      department: "Economics",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ECO301",
   },
   {
      courseCode: "PSY309",
      courseTitle: "Cognitive Psychology",
      department: "Psychology",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "PSY201",
   },
   {
      courseCode: "SOC329",
      courseTitle: "Sociology of Family II",
      department: "Sociology",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC201",
   },
   {
      courseCode: "BIO299",
      courseTitle: "Genetics II",
      department: "Biology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO101",
   },
   {
      courseCode: "ART309",
      courseTitle: "Art History II",
      department: "Art",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ART201",
   },
   {
      courseCode: "MUS419",
      courseTitle: "Music Composition II",
      department: "Music",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "MUS301",
   },
   {
      courseCode: "HIS299",
      courseTitle: "World History II",
      department: "History",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "HIS101",
   },
   {
      courseCode: "POL319",
      courseTitle: "International Relations II",
      department: "Political Science",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "POL201",
   },
   {
      courseCode: "PHI419",
      courseTitle: "Philosophical Ethics II",
      department: "Philosophy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHI301",
   },
];

export function checkForDuplicates(courseList: any) {
   const courseCodes = new Set();
   const duplicates: [] = [];

   courseList.forEach((course: CourseProps) => {
      if (courseCodes.has(course?.courseCode)) {
         // @ts-ignore
         duplicates.push(course?.courseCode);
      } else {
         courseCodes.add(course?.courseCode);
      }
   });

   return duplicates;
}
