export const departments = [
   {
      departmentName: "Software Engineering",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Cyber Security",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Computer Science",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Information System",
      faculty: "Computing",
      password: "secured",
   },
   {
      departmentName: "Information Technology",
      faculty: "Computing",
      password: "secured",
   },
];

export const courses = [
   {
      courseCode: "SWE321",
      courseTitle: "Software Testing & Quality Assurance",
      department: "Software Engineering",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "SWE221",
   },
   {
      courseCode: "CSC101",
      courseTitle: "Introduction to Computer Science",
      department: "Computer Science",
      level: "100",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "MAT202",
      courseTitle: "Linear Algebra",
      department: "Mathematics",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "MAT101",
   },
   {
      courseCode: "PHY301",
      courseTitle: "Modern Physics",
      department: "Physics",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "PHY201",
   },
   {
      courseCode: "ENG401",
      courseTitle: "Advanced English Composition",
      department: "English",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ENG301",
   },
   {
      courseCode: "CHE202",
      courseTitle: "Organic Chemistry",
      department: "Chemistry",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "CHE101",
   },
   {
      courseCode: "ECO302",
      courseTitle: "Macroeconomics",
      department: "Economics",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ECO201",
   },
   {
      courseCode: "PSY201",
      courseTitle: "Introduction to Psychology",
      department: "Psychology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "SOC401",
      courseTitle: "Sociological Theory",
      department: "Sociology",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC301",
   },
   {
      courseCode: "BIO203",
      courseTitle: "Genetics I",
      department: "Biology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO101",
   },
   {
      courseCode: "ART301",
      courseTitle: "Art History I",
      department: "Art",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ART201",
   },
   {
      courseCode: "MUS401",
      courseTitle: "Music Composition I",
      department: "Music",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "MUS301",
   },
   {
      courseCode: "HIS201",
      courseTitle: "World History I",
      department: "History",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "HIS101",
   },
   {
      courseCode: "POL303",
      courseTitle: "International Relations I",
      department: "Political Science",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "POL201",
   },
   {
      courseCode: "PHI401",
      courseTitle: "Philosophical Ethics I",
      department: "Philosophy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHI301",
   },
   {
      courseCode: "GEO201",
      courseTitle: "Geography of Cities I",
      department: "Geography",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "GEO101",
   },
   {
      courseCode: "BUS302",
      courseTitle: "Business Ethics I",
      department: "Business",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "BUS201",
   },
   {
      courseCode: "ANT201",
      courseTitle: "Cultural Anthropology I",
      department: "Anthropology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "ARC401",
      courseTitle: "Architectural Design I",
      department: "Architecture",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ARC301",
   },
   {
      courseCode: "EDU301",
      courseTitle: "Educational Psychology I",
      department: "Education",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "EDU201",
   },
   {
      courseCode: "ENV201",
      courseTitle: "Environmental Science I",
      department: "Environmental Science",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "LING401",
      courseTitle: "Linguistics I",
      department: "Linguistics",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "LING301",
   },
   {
      courseCode: "MED202",
      courseTitle: "Media Studies",
      department: "Media Studies",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "MED101",
   },
   {
      courseCode: "NUR302",
      courseTitle: "Community Health Nursing",
      department: "Nursing",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "NUR201",
   },
   {
      courseCode: "PHARM401",
      courseTitle: "Pharmacology",
      department: "Pharmacy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHARM301",
   },
   {
      courseCode: "RAD201",
      courseTitle: "Radiology Techniques",
      department: "Radiology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "RAD101",
   },
   {
      courseCode: "SOC202",
      courseTitle: "Social Problems",
      department: "Sociology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC101",
   },
   {
      courseCode: "SWK401",
      courseTitle: "Social Work Practice",
      department: "Social Work",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "SWK301",
   },
   {
      courseCode: "THE301",
      courseTitle: "Theatre Arts",
      department: "Theatre Arts",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "THE201",
   },
   {
      courseCode: "AGR202",
      courseTitle: "Agricultural Economics",
      department: "Agricultural Economics",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "AGR101",
   },
   {
      courseCode: "BIO401",
      courseTitle: "Advanced Biology",
      department: "Biology",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO301",
   },
   {
      courseCode: "CHM201",
      courseTitle: "Inorganic Chemistry",
      department: "Chemistry",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "CHM101",
   },
   {
      courseCode: "ECO402",
      courseTitle: "Microeconomics",
      department: "Economics",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ECO301",
   },
   {
      courseCode: "PSY301",
      courseTitle: "Cognitive Psychology",
      department: "Psychology",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "PSY201",
   },
   {
      courseCode: "SOC301",
      courseTitle: "Sociology of Family",
      department: "Sociology",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "SOC201",
   },
   {
      courseCode: "BIO202",
      courseTitle: "Genetics II",
      department: "Biology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "BIO101",
   },
   {
      courseCode: "ART302",
      courseTitle: "Art History II",
      department: "Art",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "ART201",
   },
   {
      courseCode: "MUS402",
      courseTitle: "Music Composition II",
      department: "Music",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "MUS301",
   },
   {
      courseCode: "HIS202",
      courseTitle: "World History II",
      department: "History",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "HIS101",
   },
   {
      courseCode: "POL302",
      courseTitle: "International Relations II",
      department: "Political Science",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "POL201",
   },
   {
      courseCode: "PHI402",
      courseTitle: "Philosophical Ethics II",
      department: "Philosophy",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "PHI301",
   },
   {
      courseCode: "GEO202",
      courseTitle: "Geography of Cities II",
      department: "Geography",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: "GEO101",
   },
   {
      courseCode: "BUS301",
      courseTitle: "Business Ethics II",
      department: "Business",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "BUS201",
   },
   {
      courseCode: "ANT202",
      courseTitle: "Cultural Anthropology II",
      department: "Anthropology",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "ARC402",
      courseTitle: "Architectural Design II",
      department: "Architecture",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "ARC301",
   },
   {
      courseCode: "EDU302",
      courseTitle: "Educational Psychology II",
      department: "Education",
      level: "300",
      unit: "3",
      courseStatus: "C",
      preReq: "EDU201",
   },
   {
      courseCode: "ENV202",
      courseTitle: "Environmental Science II",
      department: "Environmental Science",
      level: "200",
      unit: "3",
      courseStatus: "C",
      preReq: null,
   },
   {
      courseCode: "LING402",
      courseTitle: "Linguistics II",
      department: "Linguistics",
      level: "400",
      unit: "3",
      courseStatus: "C",
      preReq: "LING301",
   },
];
