import type { Metadata } from "next";
import "../globals.css";
import { accounts } from "./data";
import { Layout } from "@/components/layout";
import { cookies } from "next/headers";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   const layout = cookies().get("react-resizable-panels:layout");
   const collapsed = cookies().get("react-resizable-panels:collapsed");

   const defaultLayout = layout ? JSON.parse(layout.value) : undefined;
   const defaultCollapsed =
      collapsed && collapsed.value !== undefined
         ? JSON.parse(collapsed.value)
         : undefined;

   return (
      <html lang="en">
         <body className="relative flex h-screen w-screen overflow-hidden">
            <Layout
               accounts={accounts}
               defaultLayout={defaultLayout}
               defaultCollapsed={defaultCollapsed}
               navCollapsedSize={4}
            >
               {children}
            </Layout>
         </body>
      </html>
   );
}
